version: 2

sources:
  - name: saleslt
    schema: saleslt
    description: This is the adventureworks database loaded into bronze
    tables:
      - name: address
      - name: customer
      - name: customeraddress